clean up sql and build script

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -16,18 +16,18 @@ then
 fi
 
 # Confirm database exists, if not create it
-if ! /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" -e "select * from users;" "$OPENSHIFT_APP_NAME" > /dev/null
+if ! /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" -e "select * from user;" "$OPENSHIFT_APP_NAME" > /dev/null
 then
     echo
-    echo "Database schema not found, importing 'drupal.sql' schema."
+    echo "Database schema not found, importing 'frogcms.sql' schema."
     echo
     /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" "$OPENSHIFT_APP_NAME" < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/frogcms.sql"
     echo
     echo "done."
     echo "=================================================="
-    echo "  Drupal-Admin login: admin"
-    echo "  Drupal-Admin password: OpenShiftAdmin"
-    echo "  Don't forget to change your drupal admin password!"
+    echo "  FrogCMS-Admin login: admin "
+    echo "  FrogCMS-Admin password: 122b7e41a3K "
+    echo "  Don't forget to change your FrogCMS admin password!"
     echo "=================================================="
 else
     echo "Database found, skipping import."
